public enum EventDefine
{
    ShowGamePanel,
    DecidePath, 
    AddSocre,
    UpdateScoreText,
    PlayerMove,
    AddDiamond,
    UpdateDiamondText,
    ShowGameOverPanel,
    ShowShopPanel,
    ShowMainPanel,
    ChangeSkin,
    ShowHint,
    ShowResetPanel, 
    ShowRankPanel,
    PlayClickAudio,
    IsMusicOn
}
